#Pandas
Pandas is a powerful, open-source Python library used for data manipulation, cleaning, and analysis.

It provides two main data structures:

1.   Series → One-dimensional (like a single column in Excel)
2.   DataFrame → Two-dimensional (like a full spreadsheet or SQL table)

Pandas makes working with structured data fast, expressive, and flexible.

    If you're working with tables, spreadsheets, or CSVs in Python—Pandas is your best friend.

#1. Series — 1D Labeled Array

In [ ]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])
print(s)
print(type(s))
s = s.astype(float)
print(s)

0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>
0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64

In [ ]:
#Custom Indexing
s = pd.Series([10, 20, 30], index=["a", "c", "m"])
print(s)
print(s["m"])

a    10
c    20
m    30
dtype: int64
30

#2. DataFrame — 2D Labeled Table
####A DataFrame is like a dictionary of Series — multiple columns with labels.

In [ ]:
data = {
    "name":["Alice", "Bob", "Charlie"],
    "age":[25, 30, 35],
    "city":["Delhi", "Mumbai", "Bangalore"]
}
df=pd.DataFrame(data)
print(df)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [ ]:
df.index = ["a", "b", "c"]
df.columns = ["Name", "Age", "City"]
df

      Name  Age       City
a    Alice   25      Delhi
b      Bob   30     Mumbai
c  Charlie   35  Bangalore

###**Creating DataFrames**

In [ ]:
#from List or Dict
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
#From NumPy Array
import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

In [ ]:
#From the Web (Example: CSV from URL)
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()
print(df.tail())

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
#From excel
df = pd.read_excel('/content/drive/MyDrive/workshop/pandas/data.xlsx')
#If you are running it locally then path must be mentioned properly
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#3. Data Selection & Filtering

###**Selecting Rows & Columns**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/workshop/pandas/data.csv")
print(df.loc[0],"\n") #select with row/column labels
print(df.iloc[0]) #select with indexing

total_bill    $16.99
tip            $1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

total_bill    $16.99
tip            $1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [ ]:
print(df.loc[0,"total_bill"],"\n")
print(df.iloc[0, 1])
print(type(df.iloc[0,1]))
print(type(df.iloc[0]))

$16.99

$1.01
<class 'str'>
<class 'pandas.core.series.Series'>

In [ ]:
#Optimised for single element access
df.at[0, "time"]

'Dinner'

In [ ]:
df.iat[0, 1]

'$1.01'

###**Filtering with Conditions**

In [ ]:
df[df["size"] >= 4].head()
# df[df["size"] >= 4]

    total_bill   tip     sex smoker  day    time  size
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
7        26.88  3.12    Male     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
13       18.43  3.00    Male     No  Sun  Dinner     4

In [ ]:
df[(df["size"] > 2) & (df["sex"] == "Male")].head()
#df[(df["size"] > 2) & (df["sex"] == "Male")]

   total_bill    tip   sex smoker  day    time  size
1      $10.34  $1.66  Male     No  Sun  Dinner     3
2      $21.01  $3.50  Male     No  Sun  Dinner     3
5      $25.29  $4.71  Male     No  Sun  Dinner     4
7      $26.88  $3.12  Male     No  Sun  Dinner     4
13     $18.43  $3.00  Male     No  Sun  Dinner     4

In [ ]:
df[(df["smoker"] > "Yes" ) | (df["sex"] == "Female")].head()
#df[(df["smoker"] > "Yes" ) | (df["sex"] == "Female")]

   total_bill    tip     sex smoker  day    time  size
0      $16.99  $1.01  Female     No  Sun  Dinner     2
4      $24.59  $3.61  Female     No  Sun  Dinner     4
11     $35.26  $5.00  Female     No  Sun  Dinner     4
14     $14.83  $3.02  Female     No  Sun  Dinner     2
16     $10.33  $1.67  Female     No  Sun  Dinner     3

###**Querying with .query()**
.query() returns a copy, not a view.

The result is a new DataFrame. Changes won't affect the original unless reassigned:

In [ ]:
filtered = df.query("sex=='Female' and day=='Sun'")
filtered.head()

   total_bill    tip     sex smoker  day    time  size
0      $16.99  $1.01  Female     No  Sun  Dinner     2
4      $24.59  $3.61  Female     No  Sun  Dinner     4
11     $35.26  $5.00  Female     No  Sun  Dinner     4
14     $14.83  $3.02  Female     No  Sun  Dinner     2
16     $10.33  $1.67  Female     No  Sun  Dinner     3

#4. Data Cleaning & Preprocessing

###**Handling Missing Values**

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/workshop/pandas/student.csv")
df2

      Name   Age  Gender       City  Marks  Attendance Department
0    Aarav  20.0    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.0  Female     Mumbai   92.0         NaN        CSE
2    Rohan   NaN    Male      Delhi    NaN        82.0        ICT
3    Anaya  19.0  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.0     NaN       Pune   88.0        88.0        NaN
5     Isha  20.0  Female      Surat   95.0        92.0        CSE
6    Arjun  21.0    Male   Vadodara    NaN         NaN        ICT
7    Meera   NaN  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.0    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.0     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.0    Male      Delhi   91.0        94.0        ECE
11    Riya  22.0  Female     Mumbai    NaN        87.0        NaN
12   Karan   NaN    Male       Pune   84.0        83.0        CSE
13   Nisha  21.0  Female      Surat   73.0         NaN        ICT
14   Rahul  20.0    Male   Vadodara   87.0        89.0        ECE

In [ ]:
print(df2.isnull(),"\n")
print(df2.isnull().sum())

     Name    Age  Gender   City  Marks  Attendance  Department
0   False  False   False  False  False       False       False
1   False  False   False  False  False        True       False
2   False   True   False  False   True       False       False
3   False  False   False   True  False       False       False
4   False  False    True  False  False       False        True
5   False  False   False  False  False       False       False
6   False  False   False  False   True        True       False
7   False   True   False  False  False       False       False
8   False  False   False  False  False       False       False
9   False  False    True   True  False       False       False
10  False  False   False  False  False       False       False
11  False  False   False  False   True       False        True
12  False   True   False  False  False       False       False
13  False  False   False  False  False        True       False
14  False  False   False  False  False       False       False

Name          0
Age           3
Gender        2
City          2
Marks         3
Attendance    3
Department    2
dtype: int64

In [ ]:
# df2.fillna(0)         # Replace NaN with 0
df2["Age"]=df2["Age"].fillna(df2["Age"].mean()) # Replace with mean
df2

      Name        Age  Gender       City  Marks  Attendance Department
0    Aarav  20.000000    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female     Mumbai   92.0         NaN        CSE
2    Rohan  20.666667    Male      Delhi    NaN        82.0        ICT
3    Anaya  19.000000  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.000000     NaN       Pune   88.0        88.0        NaN
5     Isha  20.000000  Female      Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male   Vadodara    NaN         NaN        ICT
7    Meera  20.666667  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.000000    Male      Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female     Mumbai    NaN        87.0        NaN
12   Karan  20.666667    Male       Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female      Surat   73.0         NaN        ICT
14   Rahul  20.000000    Male   Vadodara   87.0        89.0        ECE

In [ ]:
df2["Marks"] = df2["Marks"].fillna(0)
df2

      Name        Age  Gender       City  Marks  Attendance Department
0    Aarav  20.000000    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female     Mumbai   92.0         NaN        CSE
2    Rohan  20.666667    Male      Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.000000     NaN       Pune   88.0        88.0        NaN
5     Isha  20.000000  Female      Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male   Vadodara    0.0         NaN        ICT
7    Meera  20.666667  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.000000    Male      Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female     Mumbai    0.0        87.0        NaN
12   Karan  20.666667    Male       Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female      Surat   73.0         NaN        ICT
14   Rahul  20.000000    Male   Vadodara   87.0        89.0        ECE

In [ ]:
df2.loc[0:7, "Attendance"] = df2.loc[0:7, "Attendance"].ffill()
df2

      Name        Age  Gender       City  Marks  Attendance Department
0    Aarav  20.000000    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female     Mumbai   92.0        90.0        CSE
2    Rohan  20.666667    Male      Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.000000     NaN       Pune   88.0        88.0        NaN
5     Isha  20.000000  Female      Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male   Vadodara    0.0        92.0        ICT
7    Meera  20.666667  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.000000    Male      Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female     Mumbai    0.0        87.0        NaN
12   Karan  20.666667    Male       Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female      Surat   73.0         NaN        ICT
14   Rahul  20.000000    Male   Vadodara   87.0        89.0        ECE

In [ ]:
df2.loc[7:, "Attendance"] = df2.loc[7:, "Attendance"].bfill()
df2

      Name        Age  Gender       City  Marks  Attendance Department
0    Aarav  20.000000    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female     Mumbai   92.0        90.0        CSE
2    Rohan  20.666667    Male      Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.000000     NaN       Pune   88.0        88.0        NaN
5     Isha  20.000000  Female      Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male   Vadodara    0.0        92.0        ICT
7    Meera  20.666667  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.000000    Male      Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female     Mumbai    0.0        87.0        NaN
12   Karan  20.666667    Male       Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female      Surat   73.0        89.0        ICT
14   Rahul  20.000000    Male   Vadodara   87.0        89.0        ECE

In [ ]:
df2["Department"] = df2["Department"].fillna("CSBS")
df2

      Name        Age  Gender       City  Marks  Attendance Department
0    Aarav  20.000000    Male  Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female     Mumbai   92.0        90.0        CSE
2    Rohan  20.666667    Male      Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female        NaN   78.0        95.0        ECE
4   Vivaan  22.000000     NaN       Pune   88.0        88.0       CSBS
5     Isha  20.000000  Female      Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male   Vadodara    0.0        92.0        ICT
7    Meera  20.666667  Female     Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male  Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN        NaN   89.0        91.0        ICT
10  Aditya  20.000000    Male      Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female     Mumbai    0.0        87.0       CSBS
12   Karan  20.666667    Male       Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female      Surat   73.0        89.0        ICT
14   Rahul  20.000000    Male   Vadodara   87.0        89.0        ECE

In [ ]:
#.replace() → Replace specific values
df2["City"]=df2["City"].fillna("Gandhinagar")
df2

      Name        Age  Gender         City  Marks  Attendance Department
0    Aarav  20.000000    Male    Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female       Mumbai   92.0        90.0        CSE
2    Rohan  20.666667    Male        Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female  Gandhinagar   78.0        95.0        ECE
4   Vivaan  22.000000     NaN         Pune   88.0        88.0       CSBS
5     Isha  20.000000  Female        Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male     Vadodara    0.0        92.0        ICT
7    Meera  20.666667  Female       Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male    Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN  Gandhinagar   89.0        91.0        ICT
10  Aditya  20.000000    Male        Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female       Mumbai    0.0        87.0       CSBS
12   Karan  20.666667    Male         Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female        Surat   73.0        89.0        ICT
14   Rahul  20.000000    Male     Vadodara   87.0        89.0        ECE

In [ ]:
df2.loc[3,"City"]=df2.loc[3,"City"].replace("Gandhinagar","Mehsana")
df2

      Name        Age  Gender         City  Marks  Attendance Department
0    Aarav  20.000000    Male    Ahmedabad   85.0        90.0        ICT
1     Diya  21.000000  Female       Mumbai   92.0        90.0        CSE
2    Rohan  20.666667    Male        Delhi    0.0        82.0        ICT
3    Anaya  19.000000  Female      Mehsana   78.0        95.0        ECE
4   Vivaan  22.000000     NaN         Pune   88.0        88.0       CSBS
5     Isha  20.000000  Female        Surat   95.0        92.0        CSE
6    Arjun  21.000000    Male     Vadodara    0.0        92.0        ICT
7    Meera  20.666667  Female       Rajkot   81.0        85.0        ECE
8    Kabir  23.000000    Male    Ahmedabad   76.0        79.0        CSE
9    Sanya  19.000000     NaN  Gandhinagar   89.0        91.0        ICT
10  Aditya  20.000000    Male        Delhi   91.0        94.0        ECE
11    Riya  22.000000  Female       Mumbai    0.0        87.0       CSBS
12   Karan  20.666667    Male         Pune   84.0        83.0        CSE
13   Nisha  21.000000  Female        Surat   73.0        89.0        ICT
14   Rahul  20.000000    Male     Vadodara   87.0        89.0        ECE